import random 
from transaction import Transaction

class Peer:
    def __init__(self, id) -> None:
        self.id = id
        self.neighbors = []
        self.speed = "" # slow or fast 
        self.cpu = ""   # low or high

        self.routing_table = {}
    
    def add_neighbor(self, neighbor):
        self.neighbors.append(neighbor)

    def disconnect_peer(self):
        self.neighbors = []
    
    def generate_transactions(self, Ttx, time, peers):
        # generate transaction for block
        # send transaction to neighbors
        # Each peer generates transactions randomly in time. The interarrival between transactions generated by
        # time is between 0 to time. generate transactions 
        # any peer is chosen from an exponential distribution whose mean time(Ttx) can be set as a parameter of the
        transactions = []
        times = []
        start_time = 0
        while start_time < time:
            t = random.expovariate(1/Ttx)
            start_time += t
            times.append(start_time)
        for t in times:
            # choose a random peer
            receiver = random.choice(peers)
            while receiver == self:
                receiver = random.choice(peers)
            # generate a random transaction id by hashing the sender, receiver and time
            id = hash(str(self.id) + str(receiver.id) + str(t))
            
            transactions.append(Transaction(id, self, receiver, 1, t))
        return transactions
    
    def forward(self, transaction):
        # The structure of self.routing_table is:
        # {recipient_peer: [list of TxIDs either sent to or received from this peer]}

        for n in self.neighbors:
            id = transaction.id
            if n in self.routing_table.keys():
                # Send this transaction to that neighbor some how
                if id not in self.routing_table[n]:
                    self.routing_table[n].append(id)            
            else:
                # Send this transaction to that neighbor some how
                self.routing_table[n] = [id]
